### ISSUE TITLE
COMANDO: !unban

### ISSUE THREAD

**Issue by kjkGustavo** [he4rt/He4rt-Bot#5]
Ao utilizar o comando "!unban" remover o banimento do usuário do servidor;
Após ser removido o banimento enviar uma mensagem em um canal definido na .env.

Comando: !unban (usuário) (motivo)
Permissão para uso: "MANAGE_GUILD"

**Comment by marcopandolfo** [comment]
Feito

**Comment by kjkGustavo** [comment]
Obrigado.
