### ISSUE TITLE
Comando: niquel

### ISSUE THREAD

**Issue by kjkGustavo** [he4rt/He4rt-Bot#64]
Comando de um jogo de gambling.

**Como funciona:**
O bot deve responder se o usuário ganhou ou perdeu na roleta com a lib `slot-machine`; 

**Comando:** !niquel
**Permissão para uso:** Roles: []
**Inspiração:** https://github.com/he4rt/He4rt-Bot/blob/master/src/commands/cacaniquel.js (Código antigo)

**Comment by JVictorV** [comment]
Posso fazer esse, a API ainda funciona?

**Comment by kjkGustavo** [comment]
Opa, funciona sim 👌
