### ISSUE TITLE
COMANDO: temp-ban

### ISSUE THREAD

**Issue by kjkGustavo** [he4rt/He4rt-Bot#8]
Ao usar o comando "!tempban" irá banir um usuário temporariamente do servidor.

**Como funciona:**
Ao banir mandar uma mensagem para o usuário informando que foi banido;
Enviar mensagem no canal de punições.

**Comando:** !tempban (@usuário) (minutos) (motivo)
**Permissão para uso:** "KICK_MEMBERS "
**Motivo:** Estou sem tempo para fazer hoje.. Se alguém quiser ajudar! <3

**Comment by marcopandolfo** [comment]
Alguém sabe como posso fazer para contar o tempo até do unban? Algum timer para o node que quando você reinicie o bot, não se perca tudo, porque fica contando na memória da aplicação
Pesquisei algumas libs de timer mas todas ficam contando na memória, e por isso se faltar 10 mim para o unban e o bot for reiniciado, a contagem acaba e a pessoa não vai ser desbanida
Consigo fazer a base do comando, mas não sei como resolver essa parte do timer

**Comment by EduardoRFS** [comment]
@marcopandolfo nesse caso o ideal seria colocar na reason do ban o timer e ter um polling para ele ficar verificando do tipo "já passou o tempo?". Afinal não temos como persistir a não ser que integremos uma database na nossa aplicação.

Talvez na reason colocar algo tipo `[10h]` e depois vc concatena o motivo do ban. Dai da para extrair a informação e validar.

**Comment by marcopandolfo** [comment]
Ok obrigado, amanha vou estudar sobre pra tentar fazer esse sistema de polling, qualquer coisa mando mensagem
