### ISSUE TITLE
Bot de apostas parou de funcionar

### ISSUE THREAD

**Issue by rafasilveira** [he4rt/He4rt-Bot#89]
## Comandos utilizados:
```
!coins
!flip 8
!corrida 10
!corrida 10
!flip 20
!flip 30
!coins
```

## Resultado esperado
Inicial: 8128 moedas
Flip 1: 8120 moedas
Corrida 1: 8110 moedas
Corrida 2: 8100 moedas
Flip 2: 8080 moedas
Flip 3: 8095 moedas

## Resultado encontrado
<img width="585" alt="Screen Shot 2020-12-07 at 09 57 57" src="https://user-images.githubusercontent.com/64478636/101353761-e6878380-3872-11eb-8b3f-ba4911618b8d.png">

**Comment by kjkGustavo** [comment]
Na nova versão do bot será corrigido este problema. Obrigado por contribuir para a comunidade :purple_heart:
