### ISSUE TITLE
Bug: !continuar roda varias vezes e timeout

### ISSUE THREAD

**Issue by EduardoRFS** [he4rt/He4rt-Bot#9]
### Problema
O !continuar pode ser rodado varias vezes e vai iniciar varios processos de seleção.

### O que fazer
Colocar um cooldown no comando e dar uma mensagem de aviso de timeout, quando o usuario não responde a mensagem, talvez permitindo extender o tempo de resposta.

### Ajuda necessária
Preciso de duas mensagens, uma para o timeout do comando e uma para quando o comando estiver em cooldown.

**Comment by EduardoRFS** [comment]
Irei fazer hoje durante a live, por isso marquei a mim mesmo

**Comment by kjkGustavo** [comment]
**Excedeu o tempo de resposta:**
`const timeout = new Discord.RichEmbed()
        .setTitle('``❌`` Tempo limite de resposta excedido.')
        .setDescription('Utilize `!continuar` para terminar sua apresentação.')
        .setColor('#36393E');`

**Cooldown para utilizar o comando**
`const cooldown = new Discord.RichEmbed()
        .setTitle('``❌`` Você já utilizou este comando, verifique sua DM para mais informações.')
        .setColor('#36393E');`

**Erro ao enviar a mensagem no privado**
Colocar uma mensagem(.catch) ao enviar a DM:
`const error = new Discord.RichEmbed()
        .setTitle('``❌`` Ops, seu privado está desativado e não consigo enviar algumas informações. 😟')
        .setColor('#36393E');`
